/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.csu.ui;

/**
 *
 * @author csu_cangkui
 */
public class IPPacketsMainFrameInReverse extends javax.swing.JFrame {

    /** Creates new form IPPacketsMainFrame */
    public IPPacketsMainFrameInReverse() {
        this.setTitle("IP Packects Cratcher");
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        control = new javax.swing.JToolBar();
        btn_start = new java.awt.Button();
        gaplabel = new java.awt.Label();
        btn_stop = new java.awt.Button();
        gaplabel1 = new java.awt.Label();
        button4 = new java.awt.Button();
        list = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ip_list = new javax.swing.JTable();
        page_ctrl = new javax.swing.JToolBar();
        gaplabel3 = new java.awt.Label();
        btn_pre = new javax.swing.JButton();
        gaplabel2 = new java.awt.Label();
        btn_next = new javax.swing.JButton();
        gaplabel4 = new java.awt.Label();
        jLabel1 = new javax.swing.JLabel();
        detail = new javax.swing.JPanel();
        detail_info_tree = new javax.swing.JScrollPane();
        info_tree = new javax.swing.JTree();
        menu_list = new javax.swing.JMenuBar();
        menu_sys = new javax.swing.JMenu();
        exit = new javax.swing.JMenuItem();
        menu_cap = new javax.swing.JMenu();
        menu_help = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        control.setRollover(true);

        btn_start.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        btn_start.setLabel("Start");
        btn_start.setMaximumSize(new java.awt.Dimension(57, 32767));
        btn_start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_startActionPerformed(evt);
            }
        });
        control.add(btn_start);

        gaplabel.setMaximumSize(new java.awt.Dimension(7, 32767));
        gaplabel.setMinimumSize(new java.awt.Dimension(7, 22));
        gaplabel.setText("  ");
        control.add(gaplabel);

        btn_stop.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        btn_stop.setLabel("Stop");
        btn_stop.setMaximumSize(new java.awt.Dimension(57, 32767));
        control.add(btn_stop);

        gaplabel1.setMaximumSize(new java.awt.Dimension(7, 32767));
        gaplabel1.setMinimumSize(new java.awt.Dimension(7, 22));
        gaplabel1.setText("  ");
        control.add(gaplabel1);

        button4.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        button4.setLabel("Config");
        button4.setMaximumSize(new java.awt.Dimension(57, 32767));
        control.add(button4);

        list.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "IP Packet List", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Courier New", 0, 18))); // NOI18N

        ip_list.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        ip_list.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "UDP", "2021/6/11 15:23:16"},
                {"2", "TCP", "2021/6/11 15:23:16"},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Identifier", "Protocol Type", "Catch Time"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ip_list.setRowHeight(30);
        ip_list.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(ip_list);
        if (ip_list.getColumnModel().getColumnCount() > 0) {
            ip_list.getColumnModel().getColumn(0).setResizable(false);
            ip_list.getColumnModel().getColumn(1).setResizable(false);
            ip_list.getColumnModel().getColumn(2).setResizable(false);
            ip_list.getColumnModel().getColumn(2).setPreferredWidth(120);
        }

        page_ctrl.setFloatable(false);
        page_ctrl.setRollover(true);
        page_ctrl.setMaximumSize(new java.awt.Dimension(84, 20));
        page_ctrl.setMinimumSize(new java.awt.Dimension(84, 20));
        page_ctrl.setPreferredSize(new java.awt.Dimension(100, 20));

        gaplabel3.setMaximumSize(new java.awt.Dimension(7, 32767));
        gaplabel3.setMinimumSize(new java.awt.Dimension(7, 20));
        gaplabel3.setPreferredSize(new java.awt.Dimension(10, 20));
        gaplabel3.setText("  ");
        page_ctrl.add(gaplabel3);

        btn_pre.setText("previous");
        btn_pre.setFocusable(false);
        btn_pre.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_pre.setMaximumSize(new java.awt.Dimension(71, 27));
        btn_pre.setMinimumSize(new java.awt.Dimension(71, 27));
        btn_pre.setPreferredSize(new java.awt.Dimension(71, 27));
        btn_pre.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_pre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_preActionPerformed(evt);
            }
        });
        page_ctrl.add(btn_pre);

        gaplabel2.setMaximumSize(new java.awt.Dimension(7, 32767));
        gaplabel2.setMinimumSize(new java.awt.Dimension(7, 22));
        gaplabel2.setText("  ");
        page_ctrl.add(gaplabel2);

        btn_next.setText("next");
        btn_next.setFocusable(false);
        btn_next.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_next.setMaximumSize(new java.awt.Dimension(71, 27));
        btn_next.setMinimumSize(new java.awt.Dimension(71, 27));
        btn_next.setPreferredSize(new java.awt.Dimension(71, 27));
        btn_next.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nextActionPerformed(evt);
            }
        });
        page_ctrl.add(btn_next);

        gaplabel4.setMaximumSize(new java.awt.Dimension(13, 32767));
        gaplabel4.setMinimumSize(new java.awt.Dimension(13, 22));
        gaplabel4.setText("     ");
        page_ctrl.add(gaplabel4);

        jLabel1.setFont(new java.awt.Font("宋体", 0, 16)); // NOI18N
        jLabel1.setText("now: 0/0");
        jLabel1.setMaximumSize(new java.awt.Dimension(64, 27));
        jLabel1.setMinimumSize(new java.awt.Dimension(64, 27));
        jLabel1.setPreferredSize(new java.awt.Dimension(64, 27));
        page_ctrl.add(jLabel1);

        javax.swing.GroupLayout listLayout = new javax.swing.GroupLayout(list);
        list.setLayout(listLayout);
        listLayout.setHorizontalGroup(
            listLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
            .addComponent(page_ctrl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        listLayout.setVerticalGroup(
            listLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(page_ctrl, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        detail.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Detailed Infomation", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Courier New", 0, 18))); // NOI18N

        info_tree.setFont(new java.awt.Font("Courier New", 0, 16)); // NOI18N
        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Detail");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Packet infomation");
        javax.swing.tree.DefaultMutableTreeNode treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("catch time:");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("catch length:");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Enthernet");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("type:");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("src MAC:");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("dst MAC:");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("IPv4");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("version:");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("priority:");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        info_tree.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        info_tree.setAlignmentX(1.0F);
        info_tree.setAlignmentY(1.0F);
        info_tree.setRowHeight(25);
        detail_info_tree.setViewportView(info_tree);

        javax.swing.GroupLayout detailLayout = new javax.swing.GroupLayout(detail);
        detail.setLayout(detailLayout);
        detailLayout.setHorizontalGroup(
            detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(detail_info_tree, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE)
        );
        detailLayout.setVerticalGroup(
            detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(detail_info_tree, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menu_list.setPreferredSize(new java.awt.Dimension(117, 33));

        menu_sys.setText("System");
        menu_sys.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 16)); // NOI18N
        menu_sys.setMaximumSize(new java.awt.Dimension(100, 32800));
        menu_sys.setMinimumSize(new java.awt.Dimension(50, 30));
        menu_sys.setPreferredSize(new java.awt.Dimension(35, 30));

        exit.setText("exit");
        exit.setPreferredSize(new java.awt.Dimension(100, 30));
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        menu_sys.add(exit);

        menu_list.add(menu_sys);

        menu_cap.setText("Capture");
        menu_cap.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 16)); // NOI18N
        menu_cap.setMaximumSize(new java.awt.Dimension(100, 32800));
        menu_cap.setMinimumSize(new java.awt.Dimension(50, 30));
        menu_cap.setPreferredSize(new java.awt.Dimension(39, 30));
        menu_list.add(menu_cap);

        menu_help.setText("Help");
        menu_help.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 16)); // NOI18N
        menu_help.setMaximumSize(new java.awt.Dimension(100, 32800));
        menu_help.setMinimumSize(new java.awt.Dimension(50, 30));
        menu_help.setPreferredSize(new java.awt.Dimension(39, 30));
        menu_list.add(menu_help);

        setJMenuBar(menu_list);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(control, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(list, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(detail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(control, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(list, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(detail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exitActionPerformed

    private void btn_startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_startActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_startActionPerformed

    private void btn_preActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_preActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_preActionPerformed

    private void btn_nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_nextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IPPacketsMainFrameInReverse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IPPacketsMainFrameInReverse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IPPacketsMainFrameInReverse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IPPacketsMainFrameInReverse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IPPacketsMainFrameInReverse().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_next;
    private javax.swing.JButton btn_pre;
    private java.awt.Button btn_start;
    private java.awt.Button btn_stop;
    private java.awt.Button button4;
    private javax.swing.JToolBar control;
    private javax.swing.JPanel detail;
    private javax.swing.JScrollPane detail_info_tree;
    private javax.swing.JMenuItem exit;
    private java.awt.Label gaplabel;
    private java.awt.Label gaplabel1;
    private java.awt.Label gaplabel2;
    private java.awt.Label gaplabel3;
    private java.awt.Label gaplabel4;
    private javax.swing.JTree info_tree;
    private javax.swing.JTable ip_list;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel list;
    private javax.swing.JMenu menu_cap;
    private javax.swing.JMenu menu_help;
    private javax.swing.JMenuBar menu_list;
    private javax.swing.JMenu menu_sys;
    private javax.swing.JToolBar page_ctrl;
    // End of variables declaration//GEN-END:variables

}
